# -*- coding: utf-8 -*-
"""python2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZosDHP8T4X3qpmU9z9LLYs1naiHMmUHK
"""

# Create a dictionary
employee = {
    "id": 101,
    "name": "Manasa",
    "salary": 50000,
    "department": "CSE"
}

print("Original Dictionary:", employee)

# Access value
print("Employee Name:", employee["name"])

# Add a new key-value pair
employee["city"] = "Vijayawada"
print("After Adding City:", employee)

# Update a value
employee["salary"] = 60000
print("After Salary Update:", employee)

# Get a value
print("Department:", employee.get("department"))

# Print keys
print("Keys:", employee.keys())

# Print values
print("Values:", employee.values())

# Print items
print("Items:", employee.items())

# Check if a key exists
if "salary" in employee:
    print("Salary key exists")

# Length of dictionary
print("Number of items:", len(employee))

# Remove an item
employee.pop("city")
print("After pop():", employee)

# Delete an item
del employee["department"]
print("After del:", employee)

# Copy dictionary
emp_copy = employee.copy()
print("Copied Dictionary:", emp_copy)

# Traverse dictionary
print("Employee Details:")
for key, value in employee.items():
    print(key, ":", value)

# Clear dictionary
employee.clear()
print("After clear():", employee)

# Create employee dictionary
employee = {
    "ID": 101,
    "Name": "Manasa",
    "Department": "CSE"
}

print("Original Employee Dictionary:")
print(employee)

# Add Salary
employee["Salary"] = 50000
print("\nAfter Adding Salary:")
print(employee)

# Update Salary
employee["Salary"] = 60000
print("\nAfter Updating Salary:")
print(employee)

# Delete Department
del employee["Department"]
print("\nAfter Deleting Department:")
print(employee)

# Display all keys and values
print("\nEmployee Details:")
for key, value in employee.items():
    print(key, ":", value)

# Search for a key
key = input("\nEnter key to search: ")

if key in employee:
    print("Key Found")
    print("Value =", employee[key])
else:
    print("Key Not Found")

# Count key-value pairs
print("\nNumber of Key-Value Pairs:", len(employee))

# Dictionary of student marks
students = {
    "Manasa": 92,
    "Ayesha": 95,
    "Teja": 88,
    "Ravi": 85,
    "Leela": 90
}

# Highest marks
highest = max(students, key=students.get)
print("\nStudent with Highest Marks:")
print(highest, "=", students[highest])

# Total and Average marks
total = sum(students.values())
average = total / len(students)

print("\nTotal Marks =", total)
print("Average Marks =", average)

# Print all student records
print("\nStudent Records:")
for name, marks in students.items():
    print(name, ":", marks)

# Dictionary of student marks
marks = {
    "Aman": 85,
    "Neha": 92,
    "Rahul": 78,
    "Priya": 95,
    "Karan": 88
}

# Find the student with the highest marks
highest = max(marks, key=marks.get)

# Display the result
print("Top Student:", highest)
print("Marks:", marks[highest])

"""Assignment: 1
1. calcultor using menu based system
*** CALCULATOR ***
 1. Addition
 2. Subtraction
 3. Multiplication
 4. Division
 5. Modulus
 6. Power
 7. Square
 8. Square Root
 9. Factorial
 10. Exit

Requirements:
* Use functions.
* Repeat until the user chooses Exit.
* Handle division by zero.
"""

import math

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error! Division by zero is not allowed."
    return a / b

def modulus(a, b):
    return a % b

def power(a, b):
    return a ** b

def square(a):
    return a * a

def square_root(a):
    if a < 0:
        return "Square root of a negative number is not possible."
    return math.sqrt(a)

def factorial(a):
    if a < 0:
        return "Factorial of a negative number is not possible."
    return math.factorial(a)

while True:
    print("\n******** CALCULATOR ********")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Modulus")
    print("6. Power")
    print("7. Square")
    print("8. Square Root")
    print("9. Factorial")
    print("10. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 10:
        print("Thank You!")
        break

    elif choice in [1, 2, 3, 4, 5, 6]:
        a = float(input("Enter first number: "))
        b = float(input("Enter second number: "))

        if choice == 1:
            print("Result =", add(a, b))
        elif choice == 2:
            print("Result =", subtract(a, b))
        elif choice == 3:
            print("Result =", multiply(a, b))
        elif choice == 4:
            print("Result =", divide(a, b))
        elif choice == 5:
            print("Result =", modulus(a, b))
        elif choice == 6:
            print("Result =", power(a, b))

    elif choice == 7:
        a = float(input("Enter a number: "))
        print("Result =", square(a))

    elif choice == 8:
        a = float(input("Enter a number: "))
        print("Result =", square_root(a))

    elif choice == 9:
        a = int(input("Enter a number: "))
        print("Result =", factorial(a))

    else:
        print("Invalid Choice! Please try again.")

"""Assignment : 2 Student* Management System
Store student details in a dictionary.
1. Add Student
 2. Display Students
 3. Search Student
 4. Update Marks
 5. Delete Student
 6. Find Topper
 7. Find Average Marks
 8. Count Students
 9. Exit

All of you complete these two Assignments.
"""

students = {}

def add_student():
    roll = input("Enter Roll Number: ")
    name = input("Enter Student Name: ")
    marks = float(input("Enter Marks: "))
    students[roll] = {"Name": name, "Marks": marks}
    print("Student Added Successfully!")

def display_students():
    if not students:
        print("No Students Found!")
    else:
        print("\nStudent Records")
        for roll, details in students.items():
            print("Roll No:", roll)
            print("Name:", details["Name"])
            print("Marks:", details["Marks"])
            print("---------------------")

def search_student():
    roll = input("Enter Roll Number: ")
    if roll in students:
        print("Name:", students[roll]["Name"])
        print("Marks:", students[roll]["Marks"])
    else:
        print("Student Not Found!")

def update_marks():
    roll = input("Enter Roll Number: ")
    if roll in students:
        marks = float(input("Enter New Marks: "))
        students[roll]["Marks"] = marks
        print("Marks Updated Successfully!")
    else:
        print("Student Not Found!")

def delete_student():
    roll = input("Enter Roll Number: ")
    if roll in students:
        del students[roll]
        print("Student Deleted Successfully!")
    else:
        print("Student Not Found!")

def find_topper():
    if not students:
        print("No Students Found!")
    else:
        topper = max(students, key=lambda x: students[x]["Marks"])
        print("Topper:")
        print("Roll No:", topper)
        print("Name:", students[topper]["Name"])
        print("Marks:", students[topper]["Marks"])

def average_marks():
    if not students:
        print("No Students Found!")
    else:
        total = 0
        for s in students.values():
            total += s["Marks"]
        avg = total / len(students)
        print("Average Marks =", avg)

def count_students():
    print("Total Students =", len(students))

while True:
    print("\n***** Student Management System *****")
    print("1. Add Student")
    print("2. Display Students")
    print("3. Search Student")
    print("4. Update Marks")
    print("5. Delete Student")
    print("6. Find Topper")
    print("7. Find Average Marks")
    print("8. Count Students")
    print("9. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        add_student()
    elif choice == 2:
        display_students()
    elif choice == 3:
        search_student()
    elif choice == 4:
        update_marks()
    elif choice == 5:
        delete_student()
    elif choice == 6:
        find_topper()
    elif choice == 7:
        average_marks()
    elif choice == 8:
        count_students()
    elif choice == 9:
        print("Thank You!")
        break
    else:
        print("Invalid Choice! Please Try Again.")