# -*- coding: utf-8 -*-
"""python1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTYGkRun3r8uQBafVrGuqI4DMiSSfHbx
"""

str="Hello";
print(str)
print(str[0])
print(str + " " + "Test")

numbers=[5,2,8,1]
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
print(len(numbers))
print(max(numbers))
print(min(numbers))
print(sum(numbers))

numbers=[10,20,30,40,50]
print(numbers[1:4])
print(numbers[:4])
print(numbers[2:])
print(numbers[::-1])

numbers=[10,20,30,40,50]
element=40
for i in range(len(numbers)):
  if numbers[i] == element:
    print("Element found at index",i)
    break
else:
      print("Element not found")

name=input("Enter your name")
print("Welcome",name)
print("Length=",len(name))

if name==name[::-1]:
  print("Palindrome")
else:
  print("Not Palindrome")

sentence = "Manogna"
vowels="aeiou"
count=0

for i in sentence.lower():
    if i in vowels:
        count+=1

print("No of vowels:",count)

sentence="Shivayadav"
vowels="AEIOU"
count=0
for i in sentence.upper():
  if i in vowels:
    count=count+1

print("No of vowela:",count)

text=input("Enter a Sentence:")
count=0
words=text.split()
for i in words:
  count += 1

print("No of Words:",count)

text = input("Enter a string: ")
ch = input("Enter a character to count: ")

count = text.count(ch)

print("Count =", count)

a="manu"
print(a)
print(a[1])
print(a[1:3])
print(" ".join([a]*2))

a=b=c=1,10.10,"manogna"
print(a)
print(b)
print(c)

name=input("Enter your name:")
age=int(input("Enter your age:"))
print("Welcome",name)

text = input("Enter a string: ")

ch = input("Enter character: ")

print("Count =", text.count(ch))

text = input("Enter a string: ")
words= text.split()
print("Count =",len(words))

numbers = [10, 20, 30, 40]

numbers.append(50)
print(numbers)

numbers.pop()
print(numbers)

numbers.remove(20)
print(numbers)

del numbers[1]
print(numbers)

lst = [10, 20, 30]
print("Original List:", lst)
lst.append(40)
print("After append(40):", lst)
lst.insert(1, 15)
print("After insert(1,15):", lst)
lst.extend([50, 60])
print("After extend([50,60]):", lst)
lst.remove(20)
print("After remove(20):", lst)
x = lst.pop()
print("Popped Element:", x)
print("After pop():", lst)
print("Index of 30:", lst.index(30))
lst.append(30)
print("After append(30):", lst)
print("Count of 30:", lst.count(30))
lst.sort()
print("After sort():", lst)
lst.reverse()
print("After reverse():", lst)
new_lst = lst.copy()
print("Copied List:", new_lst)
del lst[1]
print("After del lst[1]:", lst)
lst.clear()
print("After clear():", lst)

str=[ ];
print(str)

numbers = [10, 20, 30, 40, 50]

element = 30

if element in numbers:
    print("Element Found")
else:
    print("Element Not Found")

numbers = [10, 20, 30, 40, 50]

numbers.reverse()
print(numbers)

numbers = [10, 20, 30, 40, 50]
print(numbers[::-1])

numbers = [10, 20, 10, 30, 10]

print(numbers.count(10))

numbers = [10, 15, 20, 25, 30]

for num in numbers:
    if num % 2 == 0:
        print(num)

numbers = [12, 45, 7, 89, 23]

numbers.sort()

print("Second Largest =", numbers[-2])

numbers = [10, 20, 10, 30, 20, 40]
numbers = list(set(numbers))
print(numbers)